name: Check free games

on:
  schedule:
    # Every hours
    - cron: '0 0 * * *'
    - cron: '0 1-23 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

env:
  firebaseCred: ${{ secrets.FIREBASECRED }}
  firebaseConfig: ${{ secrets.FIREBASECONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version needed

      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute script # run main.py
        run: python main.py --mode firestore
