name: Check free games

on:
  schedule: # Twice a day
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:

env:
  firebaseCred: ${{ secrets.FIREBASECRED }}
  firebaseConfig: ${{ secrets.FIREBASECONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: execute script # run main.py
        run: python main.py --mode firestore
